spring:
  jpa:
    hibernate:
      ddl-auto: validate
security:
  cors:
    allowed-origins: https://expin.duckdns.org, http://expin.duckdns.org
  jwt:
    session-expiration-minutes: 15
    refresh-expiration-minutes: 30
